apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-node-src
  labels:
    app.kubernetes.io/name: pulsar-node-src
    app.kubernetes.io/part-of: my-cluster
    app.kubernetes.io/version: "{{ .Values.image.tag | trunc 64 }}"
    helm.sh/chart: pulsar-node-{{.Chart.Version}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pulsar-node-src
      app.kubernetes.io/part-of: my-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pulsar-node-src
        app.kubernetes.io/part-of: my-cluster
        app.kubernetes.io/version: "{{ .Values.image.tag | trunc 64 }}"
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      containers:
        - name: pulsar-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TYPE
              value: SOURCE
            - name: TIMER1
              value: {{ .Values.timer1 | quote }}
            - name: TIMER2
              value: {{ .Values.timer2 | quote }}
            - name: COUNT
              value: {{ .Values.count | quote }}
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-node-dst
  labels:
    app.kubernetes.io/name: pulsar-node
    app.kubernetes.io/part-of: my-cluster
    app.kubernetes.io/version: "{{ .Values.image.tag | trunc 64 }}"
    helm.sh/chart: pulsar-node-{{.Chart.Version}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pulsar-node
      app.kubernetes.io/part-of: my-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pulsar-node
        app.kubernetes.io/part-of: my-cluster
        app.kubernetes.io/version: "{{ .Values.image.tag | trunc 64 }}"
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      containers:
        - name: pulsar-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TYPE
              value: DESTINATION
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}