name: kafka-node

image:
  repository: "docker.io/nettivastaava/kafka-node"
  tag: "latest"
  pullPolicy: Always

securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 100m

timer1: 1000
timer2: 5000
count: 3
poll: 400


